#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule Gimp desktop='^8' state=floating follow=on

setxkbmap -option srvrkeys:none
prismlauncher -l IEEEKioskMods
